"""initial postgres schema

The whole schema as of the move to Postgres (2026-09-23). The fourteen SQLite
revisions before it were squashed away rather than ported: they were full of
SQLite-only DDL and the Postgres database started empty. Their history lives in
the `*.db` backups and in git.

Revision ID: 0001
Revises:
Create Date: 2026-09-23 07:45:37.149610

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cities_slug"), "cities", ["slug"], unique=True)
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "carousels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_carousels_city_id"), "carousels", ["city_id"], unique=False)
    op.create_index(op.f("ix_carousels_created_at"), "carousels", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_carousels_last_downloaded_at"), "carousels", ["last_downloaded_at"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("feed_url", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("publisher_group", sa.String(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("is_local_outlet", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("category_map", sa.JSON(), nullable=False),
        sa.Column(
            "fetch_interval_minutes", sa.Integer(), server_default=sa.text("30"), nullable=False
        ),
        sa.Column("etag", sa.String(), nullable=True),
        sa.Column("last_modified", sa.String(), nullable=True),
        sa.Column("cache_max_age_seconds", sa.Integer(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("canonical_url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("body_text", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("feed_position", sa.Integer(), nullable=True),
        sa.Column("category_raw", sa.String(), nullable=True),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("is_city_relevant", sa.Boolean(), nullable=True),
        sa.Column("relevance_confidence", sa.Float(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("emotional_salience", sa.String(), nullable=True),
        sa.Column("audience_breadth", sa.String(), nullable=True),
        sa.Column("impact", sa.String(), nullable=True),
        sa.Column("novelty", sa.String(), nullable=True),
        sa.Column("human_interest", sa.String(), nullable=True),
        sa.Column("timeliness", sa.String(), nullable=True),
        sa.Column("visual_potential", sa.String(), nullable=True),
        sa.Column("category_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sensitivity_flags", sa.JSON(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["cities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_articles_content_hash"), "articles", ["content_hash"], unique=False)
    op.create_table(
        "carousel_slides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("carousel_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("article_id", sa.String(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("clipped", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(["carousel_id"], ["carousels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_carousel_slides_article_id"), "carousel_slides", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_carousel_slides_carousel_id"), "carousel_slides", ["carousel_id"], unique=False
    )
    op.create_table(
        "selections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column("engagement", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("score_version", sa.Integer(), nullable=True),
        sa.Column("sort", sa.String(), nullable=True),
        sa.Column("carousel_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(["carousel_id"], ["carousels.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_selections_article_id"), "selections", ["article_id"], unique=False)
    op.create_index(op.f("ix_selections_carousel_id"), "selections", ["carousel_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_selections_carousel_id"), table_name="selections")
    op.drop_index(op.f("ix_selections_article_id"), table_name="selections")
    op.drop_table("selections")
    op.drop_index(op.f("ix_carousel_slides_carousel_id"), table_name="carousel_slides")
    op.drop_index(op.f("ix_carousel_slides_article_id"), table_name="carousel_slides")
    op.drop_table("carousel_slides")
    op.drop_index(op.f("ix_articles_content_hash"), table_name="articles")
    op.drop_table("articles")
    op.drop_table("sources")
    op.drop_index(op.f("ix_carousels_last_downloaded_at"), table_name="carousels")
    op.drop_index(op.f("ix_carousels_created_at"), table_name="carousels")
    op.drop_index(op.f("ix_carousels_city_id"), table_name="carousels")
    op.drop_table("carousels")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_cities_slug"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
