"""drop dead columns

Written, never read: `articles.body_text` was always NULL (no article body is
fetched), `articles.category_raw` duplicated `raw['category_raw']`, and
`sources.category_map` was never consulted — the classifier assigns category.

The downgrade restores the shape, not the values: `category_map` comes back as
`{}` on every row (server_default, or NOT NULL would fail on a non-empty table)
and the two article columns as NULL. `category_raw` can be refilled from
`raw->>'category_raw'`, which the downgrade does.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-23 10:04:25.012353

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "body_text")
    op.drop_column("articles", "category_raw")
    op.drop_column("sources", "category_map")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources",
        sa.Column(
            "category_map",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "articles", sa.Column("category_raw", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "articles", sa.Column("body_text", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.execute("update articles set category_raw = raw->>'category_raw'")
    # ### end Alembic commands ###
